### ISSUE TITLE
Bug: Folder to Exclude setting input is buggy

### ISSUE THREAD

**Issue by brimwats1** [beaussan/update-time-on-edit-obsidian#12]
See gif:
![3asWgBlETW](https://user-images.githubusercontent.com/49103046/137646876-9e3ee40f-a03b-4c41-914f-23256731fef9.gif)

I can't type in my template folder bc it autoexecutes. same thing happens on mobile

**Comment by beaussan** [comment]
Thanks for reporting it, I will see to fix it :)

**Comment by beaussan** [comment]
This is now fixed in v2.1.0 :tada: Feel free to reopen an issue if there is something else !
