### ISSUE TITLE
Bug: Settings disappear

### ISSUE THREAD

**Issue by brimwats1** [beaussan/update-time-on-edit-obsidian#13]
I made an error (used DD instead of dd) and then went to fix it but the setting disappears. Notice the difference when read date format is on vs off

![image](https://user-images.githubusercontent.com/49103046/137647105-64377bd8-e2ba-4a02-be72-dd29b89f0343.png)
![image](https://user-images.githubusercontent.com/49103046/137647107-c0487307-28d1-4f8d-b44c-681aea9c9943.png)

**Comment by JustAStudentOfTechnology** [comment]
![Capture1](https://user-images.githubusercontent.com/37562747/160298442-ee8b85fb-5345-40aa-88ec-99cecaa6f5b7.PNG)
![Capture](https://user-images.githubusercontent.com/37562747/160298443-33552208-3d0d-4de8-996d-7302c0bf7c76.PNG)
![Capture2](https://user-images.githubusercontent.com/37562747/160298444-214a918e-2a47-4740-bc27-bf6b631fa4c0.PNG)

**Comment by JustAStudentOfTechnology** [comment]
Same issue here, seems to error with the toggling of the "Enable a different read format from the write one" option.

**Comment by beaussan** [comment]
Given the settings that caused the issue is no more there, I can't reproduce the issue. Feel free to re open one if there is still an issue !
