### ISSUE TITLE
additional document reading format 

### ISSUE THREAD

**Issue by vvambo** [beaussan/update-time-on-edit-obsidian#14]
hey,

there are  already two formats integrated, I find the description a bit confusing:
yyyy-MM-dd'T'HH:mm:ssxxx
Date format  
"Date format is for read only"

And then I activate "Enable a different read format from the write one"
And I can select another "Read date format"
I'm not sure what this one does.

What I'd ask for is to have one format in viewing mode, that is "Easily readable" for example 'PP HH:mm' but the raw text in the frontmatter  (shown in editor) should probably still be a more detailed format (like the default: 'yyyy-MM-dd'T'HH:mm:ssxxx')

**Comment by beaussan** [comment]
You are right, and I have removed this option.
