### ISSUE TITLE
Date formatted as quoted string results in an error

### ISSUE THREAD

**Issue by adambro** [beaussan/update-time-on-edit-obsidian#16]
First of all: excellent plugin :smiley: I have some front matters created by Notable app in such format:
```
---
created: '2020-12-11T15:19:53.320Z'
---
```

The quotes around date cause `RangeError: Invalid time value` exception. It seems the problem is related to using grey-matter which tries to parse the above, but produces Invalid Date as a result. I noticed a [TODO to remove grey-matter](src/main.ts), which might solve the problem.

I could try to contribute a fix, if you're interested. Might need some pointers how to do that, though.

Also #8 feature could be a solution.

**Comment by beaussan** [comment]
Thanks !

It seems more an issue with your date format in the settings, try with `yyyy-MM-dd'T'HH:mm:ss'.'SSSxxx` as the parsing / write date format, if there is still an issue, let met know, but I've tested with your example string with this format and it parsed successfully.

By default the settings don't inclues the miliseconds that your format have.

But one thing that may cause an issue with your other app is the quote, from what I recall, by default the plugin don't add quotes to the timestamp, but this could be added if you need it ! :)

Let me know if this works for you and if you need the quotes, if so I can make it tomorrow, it shouldn't be a long task :)

**Comment by adambro** [comment]
Thanks for the tip, the `yyyy-MM-dd'T'HH:mm:ss'.'SSSXXX` worked. I guess it has to be `XXX` to handle UTC represented as `Z` :)

I do have a mix of few time formats in my YAML front matter. That's why #8 might be handy. Or I'll just create simple `sed` script to change all of them in place.
