### ISSUE TITLE
exclusion folder does not apply, plugin still active even after removed it

### ISSUE THREAD

**Issue by efemkay** [beaussan/update-time-on-edit-obsidian#18]
- i'm using obsidian v0.13.12, i experienced the following issues which seems to stem that any setting i do in the settings page does not apply
  - i apply folder for exclusion but the plugin still run for the files in it
  - i change the "updated" text for the fontmatter to "modified", it duplicates the date/time for both (instead replacing the "updated")
  - i removed the plugin, but it still run
- i'm using "Incremental Writing" plugin, and this created/updated text seems to (sometimes) does work play well with that plugin frontmatter -- meaning that it somewhat didn't recognise that there's already a front matter. so because of that it create a new one and push the "Incremental Writing" frontmatter down (effectively making it a part of the note)
- in the meantime, how to fix this manually?

**Comment by beaussan** [comment]
Hi, sorry for the delay. This should now be fixed as of 2.0.0. If that's still an issue, feel free to re open a new issue !

**Comment by efemkay** [comment]
Hey there. Tqs for the update. I'll give a try with the update
