### ISSUE TITLE
Feature request: Replace the `T` with a space ` `

### ISSUE THREAD

**Issue by huyz** [beaussan/update-time-on-edit-obsidian#2]
I think that replacing the `T` with a space ` ` is still valid RFC3339 https://datatracker.ietf.org/doc/html/rfc3339#section-5.6

So could you remove the `T` to make the output cleaner and more readable?

Thanks

**Comment by huyz** [comment]
Maybe you could do a simple string replace on the output of the library function?

**Comment by beaussan** [comment]
Duplicate of #3
