### ISSUE TITLE
created time is 1h off in CET

### ISSUE THREAD

**Issue by ahue** [beaussan/update-time-on-edit-obsidian#20]
## Current behavior

Plugin sets the frontmatter to the following,
```
---
created: 2022-01-12T09:12:52
updated: 2022-01-12T08:20:55
---
```
notice the difference between created and updated in the hour.

_templater_ plugin `<% tp.file.creation_date("YYYY-MM-DD'T'HH:mm:ss") %>` produces `2022-01-12T08:12:52`. 

Interestingly, it seems to be no problem with the `updated` field.

## Expected behavior

Plugin should produce the same as _templater_ example. The actual creation time of the file was 8:12:52 CET.

**Comment by beaussan** [comment]
This should now be fixed since we now rely on Obsidian's created & modify time to update the header. If that is still an issue, feel free to reopen an issue !
