### ISSUE TITLE
Gets wrong created date

### ISSUE THREAD

**Issue by skorphil** [beaussan/update-time-on-edit-obsidian#22]
The plugin writes down an edited date instead of a created date on mac os

I do believe it is because different OSs use different methods to get created date.

For a temporary workaround, I made a script to add created date to the frontmatter https://github.com/skorphil/meta_to_frontmatter

**Comment by timkgh** [comment]
For me on macOS it keeps updating _created_ date even if it already exists, and it keeps setting it back in time. There's a bug here, I had to turn off adding "Created at" if it doesn't exist. It shouldn't touch _created_ if it's already set.

**Comment by beaussan** [comment]
Hi, sorry for the delay. This should now be fixed as of 2.0.0. If that's still an issue, feel free to re open a new issue !
