### ISSUE TITLE
Not working on mobile

### ISSUE THREAD

**Issue by jodli** [beaussan/update-time-on-edit-obsidian#25]
Hey!

I'm not sure if it's just me, but this plugin is not working on mobile.
It neither adds a created nor an updated key in the frontmatter yaml :(

Also because there is no action to insert the time directly there is no workaround but to write it yourself...

You have any suggestions?

**Comment by levirs565** [comment]
I have open pull request to fix this issue. #32

**Comment by Calorion** [comment]
Is this working on mobile yet?

**Comment by bogenschlag** [comment]
Not reliably, it seems to me (at least not on i(Pad)OS). 🤷🏼‍♂️

**Comment by djsnipa1** [comment]
I have been trying to figure out what I was doing wrong. I’m on iOS as well. Is there a good alternative that anyone is using?

**Comment by beaussan** [comment]
Hi, sorry for the delay. This should now be fixed as of 2.0.0. If that's still an issue, feel free to re open a new issue !
