### ISSUE TITLE
Console logging

### ISSUE THREAD

**Issue by TfTHacker** [beaussan/update-time-on-edit-obsidian#27]
This plugin is super useful. thank you!

I noticed a lot of log info going to the console. This is ok, just for other developers it creates a lot of noise.

Maybe you could consider a debug switch in settings to disable logging (which should be the default).

**Comment by beaussan** [comment]
Hi, sorry for the delay. This should now be fixed as of 2.0.0. If that's still an issue, feel free to re open a new issue !
