### ISSUE TITLE
Not Updating Frontmatter Field Appropriatly

### ISSUE THREAD

**Issue by JustAStudentOfTechnology** [beaussan/update-time-on-edit-obsidian#29]
When creating a note with "Created" and "Modified:" as part of the frontmatter is doesn't add the date value specified after it, it just adds it to the frontmatter
![Screenshot 2022-06-25 220146](https://user-images.githubusercontent.com/37562747/175797560-c1720ba3-0d78-412c-9991-4805d0b8a17b.png)
.

**Comment by beaussan** [comment]
Hi, sorry for the delay. This should now be fixed as of 2.0.0. If that's still an issue, feel free to re open a new issue !
