### ISSUE TITLE
Plugin keeps updating file

### ISSUE THREAD

**Issue by XobSod** [beaussan/update-time-on-edit-obsidian#33]
I have strange bug (i think).
I have plugin setup to update 'Update date' in yaml header in format 'DD-MM-YYYY'. And I have file explorer set up to sort files by last modified date.

The issue is, when I update several files, the plugin works correctly (changes the yaml entry) but it keeps updating the file... I see it as files keep changing order in the file explorer as they are periodically saved again and again.

**Comment by mrienstra** [comment]
There is a similar plugin, [scambier/obsidian-auto-updated-date](https://github.com/scambier/obsidian-auto-updated-date), which is "archived" on GitHub, with this message:

> ⚠️ **DO NOT USE - BUGGY**  
> ✅ Use [Obsidian Linter](https://github.com/platers/obsidian-linter) instead.
> 
> ---
> 
> This plugin will trigger a self-feeding update loop if the same file is open on 2 different editors.

Sounds like it might be the same issue you're experiencing, guessing both plugins have the same bug.

**Comment by beaussan** [comment]
With the 2.0.0 release, this should be less of an issue. If that's still the case, we can add a delay before updating the file again to prevent loops
