### ISSUE TITLE
Feature Request: Command pallet command to force the update

### ISSUE THREAD

**Issue by jkamenik** [beaussan/update-time-on-edit-obsidian#37]
Often I am editing in a hurry, and often am done before the minimum timeout (1m) is complete.  It would be nice to have a button or something in the command pallet to simply force this update on the currently open file.

Also, and sort of related it would be nice to disable automatic update and just rely on the command pallet command.

**Comment by beaussan** [comment]
There was not a way, but I have changed the way updates are written to the file, so this shouldn't be needed as, as soon as you save, it will update the file time in the frontmatter

Closing this one in favor of #47 to centralise the discussion
