### ISSUE TITLE
Bug: "Updated" time updated without change

### ISSUE THREAD

**Issue by klieret** [beaussan/update-time-on-edit-obsidian#38]
Some of my files have their `updated` field updated even without any changes being applied to the note. 
I noticed this by looking at the differences when committing my files on git, but I could not figure out a pattern yet and I am unable to reproduce it immediately (but it has happened ever since I started using this plugin a few months ago). 

In principle, this could of course be caused by applying edits and then rolling them back, but I personally think that this is too rare to be the sole explanation for this.

Is anyone else experiencing this?

**Comment by u-ways** [comment]
@klieret Yup, I am having this issue too, did you figure out why? So far I am thinking it's either cause of git and/or perhaps how this plugin implement it's own observers.

**Comment by Inclement9** [comment]
I just reported the same issue with the created date.
https://github.com/beaussan/update-time-on-edit-obsidian/issues/41

**Comment by brunops** [comment]
I'm frequently having this issue, can't tell why it happens.
