### ISSUE TITLE
"Enable a different read format from the write one"

### ISSUE THREAD

**Issue by Inclement9** [beaussan/update-time-on-edit-obsidian#40]
What does this do? Would you explain it a little more, please?

Similar to question asked here: https://github.com/beaussan/update-time-on-edit-obsidian/issues/14#issue-1044680516

This issue thinks there might be a bug with it: https://github.com/beaussan/update-time-on-edit-obsidian/issues/13

**Comment by beaussan** [comment]
This option has now be removed.
