### ISSUE TITLE
Any way to update all files?

### ISSUE THREAD

**Issue by brunops** [beaussan/update-time-on-edit-obsidian#55]
This might be a feature request. 

Is there a way to add the frontmatter to all files? It's quite cumbersome to have to open + edit each existing file by hand to the the frontmatter added.

thanks

**Comment by beaussan** [comment]
That is a good idea! Given the plugin now relied on the times from Obsidian, this is possible. I'll try to come up with something in the settings to do it since it will mostly be a one time operation

**Comment by beaussan** [comment]
Added in 2.2.0 :tada:

**Comment by brunops** [comment]
ps: just tried it out and it worked like a charm, thanks again 😌
