### ISSUE TITLE
Created Key is overwritten

### ISSUE THREAD

**Issue by tillstuder** [beaussan/update-time-on-edit-obsidian#57]
Hello there, recently (I can't point it to a specific version) the plugin has been overwriting the `created` key with the `ctime` even if the key is already present. I've noticed this since I moved to a new laptop, where I copied all my notes to. So now when I visit old notes, the `created` key is being overwritten with the time of when I copied over the files.

Steps to reproduce:
1. Create a new note using an external text editor
2. Fill out the `created` key with an old date
3. Visit the newly created not using Obsidian
4. See how the value as been overwritten

**Comment by beaussan** [comment]
Hello, thanks for reporting ! This is now fixed in 2.2.1 :tada: 

Feel free to re open an issue if there is something else !
