### ISSUE TITLE
Type mismatch error

### ISSUE THREAD

**Issue by rzombeck** [beaussan/update-time-on-edit-obsidian#65]
I am getting a "Type mismatch, expected date & time" error on new and existing files.

Please see images attached .

![Screenshot 2023-12-14 103147](https://github.com/beaussan/update-time-on-edit-obsidian/assets/5642489/b5c4f8b4-9d55-44da-aea1-e27e8269514a)
![Screenshot 2023-12-14 103357](https://github.com/beaussan/update-time-on-edit-obsidian/assets/5642489/e818658c-73d7-4b3a-b19e-c36ff7100ca8)

**Comment by beaussan** [comment]
This is expected, since your format with the pipe is not recognised by obsidian. I don't remember if you can customize the settings for the properties in obsidian to match your format, otherwise you will have to change your format to matchs obsidian's ones (suggested in the settings).

**Comment by rzombeck** [comment]
that did it! Thanks so much. Not only for the response, but the impressive speed in which you responded.

**Comment by beaussan** [comment]
My pleasure! Thank you for using my plugin, and feel free to open any issues if you see others bugs!
