### ISSUE TITLE
support Obidian property type:Date / Date&Time

### ISSUE THREAD

**Issue by AiurArtanis** [beaussan/update-time-on-edit-obsidian#74]
it'll be nice if this plugin supports the property type:Date / Date&Time

**Comment by beaussan** [comment]
It should be ? Or maybe I'm missing something.

You have to change the type on the obsidian properties header :
<img width="342" alt="image" src="https://github.com/beaussan/update-time-on-edit-obsidian/assets/7281023/f1c81c25-150d-483d-863b-585f682dfd01">

**Comment by AiurArtanis** [comment]
> It should be ? Or maybe I'm missing something.
> 
> You have to change the type on the obsidian properties header : <img alt="image" width="342" src="https://private-user-images.githubusercontent.com/7281023/314232561-f1c81c25-150d-483d-863b-585f682dfd01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4OTg3NjYsIm5iZiI6MTcxMDg5ODQ2NiwicGF0aCI6Ii83MjgxMDIzLzMxNDIzMjU2MS1mMWM4MWMyNS0xNTBkLTQ4M2QtODYzYi01ODVmNjgyZGZkMDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjBUMDEzNDI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2ZkN2MzMzQxYjNiZmJhM2QyNTk2MDI0MGViOGQ2OGE5NzVmYTNlOTc4NjNhZDRlOTgzNWIwNTg5YjY5ODA4MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._8V9-yt0ryxl-zKSPBFPCBI0twD_RRoDg8dIoj9UsXE">

i mean create these properties as Date&Time type, so that i can search or order the note by Date&Time(e.g. DataView plugin)

**Comment by 8ugMak1r** [comment]
need this feature

**Comment by beaussan** [comment]
You just need to change the property type once in Obsidian and then it should be fine, like in my screenshot

**Comment by AiurArtanis** [comment]
> You just need to change the property type once in Obsidian and then it should be fine, like in my screenshot

yeah i just changed the type and it works well, thank u 😁
however, i still think it'll be better to initialize “create time” and "update time" into `.obsidian\types.json`
